# Generated by Django 2.1.2 on 2018-10-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
    ]
